### ISSUE TITLE
Roadmap collab

### ISSUE THREAD

**Issue by paxperscientiam** [marekdedic/imagelightbox#185]
hey @rejas @marekdedic , etc,

Let's aggregate all the ideas that we've been bouncing around into a roadmap. It'll ensure that development of `imagelightbox` moves forward in a coherent fashion.

What is a "lightbox"?
In short, it's a [modal window](https://en.wikipedia.org/wiki/Modal_window) with the background content "darkened" or obscured.

Broad questions to answer, according to [Nielson Norman Group](https://www.nngroup.com/articles/overuse-of-overlays/).

PRINCIPLES
===

- **Who** is the target audience?
Developers with graphical content to share, allowing for supplemental text
- **What** action is the user supposed to take?
...
- **When** will the overlay appear, and will it be an interruption?
`imagelightbox` is not built to annoy.
- Where will the overlay appear on the page?
...

**Scope:**
- 

GOALS
===

**Features**
- [ ] matrix (static)
- [ ] matrix (rubiks)

**Structure/logic:** see PR #163 #184 
- [ ] Adopt "dependency injection" concept. For instance, inferring the state of the image from any give point in the code is a nightmare due to the `image` variable's large scope.
- [ ] Improve handling of image loading. #22 #178 #176 

**Performance**
- [ ] Make better.

**Accessibility**
- [ ] Adheres to ...

**i18n** PR  ; issue #129
- [ ] Follows semiotic standards / best practices.

**Compatibility** see #183 #180 
- [ ]

**Maintainability**
- [ ] Auto document #106

**Comment by GenaBitu** [comment]
Hey, @rejas and @paxperscientiam if you are ok with it, I would merge develop into master and then merge the new master into all PRs to keep them up-to-date. @paxperscientiam would need to do that for all his PRs as well.

As a result, I think there are more branches to be deleted or merged. (`issue_47` and `touch_zoom` for example - for those I don't know what they are about).

**Comment by paxperscientiam** [comment]
@GenaBitu All of my open PRs are to `master`. Does that mean I have nothing to do?

**Comment by GenaBitu** [comment]
No, since this move would merge some new commits from `develop` to `master`, you would then need to merge those into your PRs

**Comment by rejas** [comment]
@GenaBitu I'm ok with it :-) Happy Xmas!

**Comment by GenaBitu** [comment]
Hi, Happy Christmas to you as well!
I've merged it.
@paxperscientiam, this created merge conflicts in #165, #173, #180 and #182. If they are to be merged (not sure for some), please merge the current master into them.

**Comment by rejas** [comment]
Got no views on it :-) Not sure if it is overkill for this little  library but if you want to I dont object. Would release a v1.0.0 this weekend though and afterwards we can go for bigger reworks like that

**Comment by marekdedic** [comment]
Yeah... Well I was thinking about making TS typings for the library, but then, well, why not actually use it... But that would be for the future for sure...

**Comment by paxperscientiam** [comment]
@marekdedic , are you interested in translating the codebase to TS? I have experience with writing jQuery plugins in TS.

**Comment by marekdedic** [comment]
Hi, check out #198. I think it is mostly converted to TS. However, this reveals some bad design decisions made previously :/

**Comment by paxperscientiam** [comment]
I'm starting to play with the code and the first area of improvement that comes to mind is that the code could be broken up into a "master" and imports.

**Comment by marekdedic** [comment]
@paxperscientiam I've added you as a collaborator so that you can work with the repo easier. Also so that you can do reviews - I would like yours on #198...

**Comment by marekdedic** [comment]
I think this is moot.
